apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express-depl
  labels:
    app: mongodb-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-express
  template:
    metadata:
      labels:
        app: mongodb-express
    spec:
      containers:
      - name: mongodb-express
        image: mongo-express:1.0.0
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME     
          valueFrom:
            secretKeyRef:
              name: system-secrets
              key: mongo-initdb-root-username
        - name:  ME_CONFIG_MONGODB_ADMINPASSWORD 
          valueFrom:
            secretKeyRef:
              name: system-secrets
              key: mongo-initdb-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: system-config
              key: database-url
        - name: ME_CONFIG_BASICAUTH
          value: "false"