apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-serv
spec:
  selector:
    app: mongodb-express
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000